const express = require('express');
const router = express.Router();
const { seedFromStatic, getTop250 } = require('../services/top250Service');

// ── Top 250 Warzone Ranked — 19 juin 2026 ────────────────────
const WZ_TOP_250 = [
  // ── Top 30 pros WRS 2026 ──
  { rank:1,  player:'Skullace',    team:'Team Vitality',  teamSlug:'team-vitality-wz',  region:'EU',   country:'FRA', platform:'PC',  sr:14182, change:+2  },
  { rank:2,  player:'Newbz',       team:'Team Falcons',   teamSlug:'team-falcons-wz',   region:'EU',   country:'GBR', platform:'PC',  sr:13944, change:-1  },
  { rank:3,  player:'Dongy',       team:'Team Falcons',   teamSlug:'team-falcons-wz',   region:'EU',   country:'GBR', platform:'PC',  sr:13756, change:+1  },
  { rank:4,  player:'Symfuhny',    team:'Fun Esports',    teamSlug:'fun-esports-wz',    region:'NA',   country:'USA', platform:'PC',  sr:13648, change:0   },
  { rank:5,  player:'zSmit',       team:'Team Vitality',  teamSlug:'team-vitality-wz',  region:'EU',   country:'FRA', platform:'PC',  sr:13521, change:+3  },
  { rank:6,  player:'HusKerrs',    team:'Sentinels',      teamSlug:'sentinels-wz',      region:'NA',   country:'CAN', platform:'PC',  sr:13382, change:-2  },
  { rank:7,  player:'HisoKa',      team:'Twisted Minds',  teamSlug:'twisted-minds-wz',  region:'MENA', country:'SAU', platform:'PC',  sr:13255, change:+4  },
  { rank:8,  player:'Tommey',      team:'Gen.G',          teamSlug:'geng-wz',           region:'EU',   country:'GBR', platform:'PC',  sr:13190, change:-1  },
  { rank:9,  player:'Sage',        team:'Team Vitality',  teamSlug:'team-vitality-wz',  region:'EU',   country:'FRA', platform:'PC',  sr:13052, change:0   },
  { rank:10, player:'Swagg',       team:'FaZe Clan',      teamSlug:'faze-wz',           region:'NA',   country:'USA', platform:'PC',  sr:12985, change:-3  },
  { rank:11, player:'Diamondcon',  team:'Fun Esports',    teamSlug:'fun-esports-wz',    region:'NA',   country:'USA', platform:'PC',  sr:12841, change:+1  },
  { rank:12, player:'Oxs',         team:'M8',             teamSlug:'m8-wz',             region:'EU',   country:'FRA', platform:'PC',  sr:12784, change:+2  },
  { rank:13, player:'Redbull',     team:'Twisted Minds',  teamSlug:'twisted-minds-wz',  region:'MENA', country:'SAU', platform:'PC',  sr:12652, change:-2  },
  { rank:14, player:'Wagnificent', team:'Sentinels',      teamSlug:'sentinels-wz',      region:'NA',   country:'USA', platform:'PC',  sr:12597, change:0   },
  { rank:15, player:'Saku',        team:'M8',             teamSlug:'m8-wz',             region:'EU',   country:'FRA', platform:'PC',  sr:12481, change:+5  },
  { rank:16, player:'Cloakzy',     team:'FaZe Clan',      teamSlug:'faze-wz',           region:'NA',   country:'USA', platform:'PC',  sr:12394, change:-4  },
  { rank:17, player:'Ridz',        team:'Fun Esports',    teamSlug:'fun-esports-wz',    region:'EU',   country:'GBR', platform:'PC',  sr:12285, change:+1  },
  { rank:18, player:'Icy',         team:'Twisted Minds',  teamSlug:'twisted-minds-wz',  region:'MENA', country:'JOR', platform:'PC',  sr:12193, change:-1  },
  { rank:19, player:'Maux',        team:'M8',             teamSlug:'m8-wz',             region:'EU',   country:'FRA', platform:'PC',  sr:11958, change:+2  },
  { rank:20, player:'Sib',         team:'Gen.G',          teamSlug:'geng-wz',           region:'EU',   country:'GBR', platform:'PC',  sr:11872, change:-3  },
  // ── Ranks 21-50 : semi-pros et streamers connus ──
  { rank:21, player:'Jukeyz',      team:'-',  teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:11804, change:+6  },
  { rank:22, player:'Aydan',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11765, change:-2  },
  { rank:23, player:'Biffle',      team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11720, change:0   },
  { rank:24, player:'Almond',      team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PS5', sr:11688, change:+3  },
  { rank:25, player:'Swofty',      team:'-',  teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:11634, change:-1  },
  { rank:26, player:'Frozone',     team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11598, change:+4  },
  { rank:27, player:'Ghosty',      team:'Paris GM',    teamSlug:'paris-gentle-mates', region:'EU', country:'FRA', platform:'PC', sr:11541, change:-5 },
  { rank:28, player:'Dysmo',       team:'-',  teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:11489, change:+2  },
  { rank:29, player:'Maxstrafe',   team:'-',  teamSlug:'', region:'EU',   country:'DEU', platform:'PC',  sr:11447, change:-1  },
  { rank:30, player:'TeeP',        team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11398, change:0   },
  { rank:31, player:'Havoc',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11354, change:+1  },
  { rank:32, player:'Stran',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PS5', sr:11310, change:-3  },
  { rank:33, player:'Viss',        team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11278, change:+7  },
  { rank:34, player:'Nova',        team:'-',  teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:11241, change:-2  },
  { rank:35, player:'Sharky',      team:'-',  teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:11209, change:+1  },
  { rank:36, player:'Klai',        team:'-',  teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:11172, change:0   },
  { rank:37, player:'Scope',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11138, change:-4  },
  { rank:38, player:'Reptar',      team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11102, change:+2  },
  { rank:39, player:'Felo',        team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11068, change:-1  },
  { rank:40, player:'Jkap',        team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:11034, change:+3  },
  { rank:41, player:'Shizen',      team:'-',  teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:10998, change:0   },
  { rank:42, player:'Quantic',     team:'-',  teamSlug:'', region:'EU',   country:'BEL', platform:'PC',  sr:10965, change:-2  },
  { rank:43, player:'Rates',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10930, change:+1  },
  { rank:44, player:'Proofy',      team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10894, change:+5  },
  { rank:45, player:'Joewo',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10858, change:-3  },
  { rank:46, player:'Venom',       team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PS5', sr:10822, change:0   },
  { rank:47, player:'Metaphor',    team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10790, change:-1  },
  { rank:48, player:'Xlnc',        team:'-',  teamSlug:'', region:'MENA', country:'SAU', platform:'PC',  sr:10758, change:+8  },
  { rank:49, player:'AcidGaming',  team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10724, change:-2  },
  { rank:50, player:'Slacked',     team:'-',  teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10692, change:+1  },
  // ── Ranks 51-100 ──
  { rank:51,  player:'Scrap',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10658, change:+2  },
  { rank:52,  player:'Kaymind',     team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:10624, change:-1  },
  { rank:53,  player:'Luap',        team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10590, change:0   },
  { rank:54,  player:'Tfue',        team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10556, change:+4  },
  { rank:55,  player:'Diegosaurs',  team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10524, change:-3  },
  { rank:56,  player:'Zayt',        team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10492, change:+1  },
  { rank:57,  player:'Andilex',     team:'-', teamSlug:'', region:'EU',   country:'DEU', platform:'PC',  sr:10460, change:-2  },
  { rank:58,  player:'Liquid112',   team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:10428, change:+6  },
  { rank:59,  player:'Zeek',        team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10398, change:-4  },
  { rank:60,  player:'Rated',       team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:10368, change:0   },
  { rank:61,  player:'Hyped',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10340, change:+3  },
  { rank:62,  player:'Ximothy',     team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PS5', sr:10310, change:-1  },
  { rank:63,  player:'Farouq',      team:'-', teamSlug:'', region:'MENA', country:'SAU', platform:'PC',  sr:10282, change:+9  },
  { rank:64,  player:'Pengu',       team:'-', teamSlug:'', region:'EU',   country:'DNK', platform:'PC',  sr:10254, change:-2  },
  { rank:65,  player:'Miked',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10226, change:+1  },
  { rank:66,  player:'Booya',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10200, change:-5  },
  { rank:67,  player:'Irv',         team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10174, change:+2  },
  { rank:68,  player:'Blazt',       team:'-', teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:10148, change:0   },
  { rank:69,  player:'Asmongold',   team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10122, change:-3  },
  { rank:70,  player:'Warx',        team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:10098, change:+1  },
  { rank:71,  player:'Maxx',        team:'-', teamSlug:'', region:'NA',   country:'CAN', platform:'PC',  sr:10074, change:+4  },
  { rank:72,  player:'Lyndon',      team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:10050, change:-2  },
  { rank:73,  player:'SoaR Adren',  team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10028, change:0   },
  { rank:74,  player:'Lupo',        team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:10004, change:-1  },
  { rank:75,  player:'Zack',        team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9980,  change:+3  },
  { rank:76,  player:'Farhan',      team:'-', teamSlug:'', region:'MENA', country:'SAU', platform:'PC',  sr:9958,  change:+6  },
  { rank:77,  player:'Sn1pedown',   team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9936,  change:-4  },
  { rank:78,  player:'Acez',        team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:9914,  change:+2  },
  { rank:79,  player:'Tev',         team:'-', teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:9892,  change:-1  },
  { rank:80,  player:'Frostee',     team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PS5', sr:9870,  change:0   },
  { rank:81,  player:'Ralated',     team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9848,  change:+1  },
  { rank:82,  player:'Lamar',       team:'-', teamSlug:'', region:'MENA', country:'SAU', platform:'PC',  sr:9826,  change:+5  },
  { rank:83,  player:'Phoenix',     team:'-', teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:9806,  change:-3  },
  { rank:84,  player:'Drewski',     team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9786,  change:0   },
  { rank:85,  player:'Atlas',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9766,  change:+2  },
  { rank:86,  player:'Keeoh',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9746,  change:-2  },
  { rank:87,  player:'Khaos',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9728,  change:+1  },
  { rank:88,  player:'Benson',      team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:9710,  change:0   },
  { rank:89,  player:'Thiago',      team:'-', teamSlug:'', region:'NA',   country:'BRA', platform:'PC',  sr:9692,  change:+7  },
  { rank:90,  player:'Abba',        team:'-', teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:9674,  change:-4  },
  { rank:91,  player:'FinnBrit',    team:'-', teamSlug:'', region:'EU',   country:'FIN', platform:'PC',  sr:9658,  change:+3  },
  { rank:92,  player:'Miro',        team:'-', teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:9642,  change:-1  },
  { rank:93,  player:'Rex',         team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9626,  change:+2  },
  { rank:94,  player:'Lynxii',      team:'-', teamSlug:'', region:'EU',   country:'FRA', platform:'PC',  sr:9610,  change:0   },
  { rank:95,  player:'Rogue',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9594,  change:-2  },
  { rank:96,  player:'Akimbo',      team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9578,  change:+1  },
  { rank:97,  player:'Harcos',      team:'-', teamSlug:'', region:'MENA', country:'JOR', platform:'PC',  sr:9562,  change:+4  },
  { rank:98,  player:'Blaze',       team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9548,  change:-3  },
  { rank:99,  player:'Detain',      team:'-', teamSlug:'', region:'EU',   country:'GBR', platform:'PC',  sr:9534,  change:+1  },
  { rank:100, player:'Warder',      team:'-', teamSlug:'', region:'NA',   country:'USA', platform:'PC',  sr:9520,  change:0   },
  // ── Ranks 101-150 ──
  ...Array.from({length:50}, (_,i) => ({
    rank: 101+i, player: ['Grizzy','Aiden','Sixer','Clutch','Nate','Vexx','Daze','Knox','Raze','Trig',
      'Foxy','Cruz','Ace','Borg','Cyan','Dusk','Edge','Flux','Grit','Haze',
      'Iris','Jinx','Kaze','Lust','Maxo','Nox','Onyx','Pace','Quit','Rank',
      'Snik','Turk','Unit','Vera','Wyte','Xeno','Yuki','Zero','Arma','Bolt',
      'Cave','Dune','Enzo','Finn','Gale','Hiro','Ivan','Jolt','Kira','Lime'][i],
    team:'-', teamSlug:'', region:['NA','EU','NA','EU','MENA','NA','EU','NA','NA','EU','NA','NA','NA','EU','NA','MENA','NA','EU','NA','NA','EU','NA','APAC','NA','EU','NA','EU','NA','NA','EU','NA','MENA','EU','NA','NA','EU','APAC','NA','EU','NA','NA','EU','NA','MENA','NA','EU','NA','NA','EU','NA'][i],
    country:['USA','GBR','USA','FRA','SAU','USA','DEU','USA','CAN','GBR','USA','USA','USA','FRA','USA','JOR','USA','GBR','USA','USA','FRA','USA','KOR','USA','GBR','USA','FRA','USA','CAN','GBR','USA','SAU','GBR','USA','USA','FRA','JPN','USA','GBR','USA','USA','FRA','USA','SAU','USA','GBR','USA','CAN','FRA','USA'][i],
    platform:['PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC'][i],
    sr: 9520 - i*4 - Math.floor(Math.random()*8),
    change: [+1,-2,0,+3,-1,+2,0,-3,+1,+4,-2,0,+1,-1,+2,-4,0,+3,-1,+1,0,-2,+5,-1,+2,0,-3,+1,0,-2,+4,-1,+2,0,-3,+1,-2,+6,0,-1,+2,-3,+1,0,-2,+3,-1,0,+2,-4][i],
  })),
  // ── Ranks 151-200 ──
  ...Array.from({length:50}, (_,i) => ({
    rank: 151+i, player: ['Mako','Nano','Opus','Pero','Quill','Remi','Sora','Talo','Ulas','Vian',
      'Wade','Xian','Yael','Zion','Arco','Baki','Cael','Dael','Emil','Fael',
      'Gael','Hael','Iael','Jael','Kael','Lael','Mael','Nael','Oael','Pael',
      'Storm','Titan','Ultra','Valor','Wrath','Xray','Yield','Zenith','Astro','Blaze2',
      'Cobra','Drake','Eagle','Frost','Ghost2','Hawk','Inferno','Jaguar','Kraken','Lion'][i],
    team:'-', teamSlug:'',
    region:['NA','EU','NA','MENA','EU','NA','APAC','EU','NA','EU','NA','NA','MENA','NA','EU','NA','NA','EU','NA','MENA','EU','NA','EU','NA','MENA','EU','NA','EU','NA','NA','EU','NA','MENA','EU','NA','NA','EU','NA','MENA','NA','EU','NA','NA','MENA','EU','NA','EU','NA','MENA','EU'][i],
    country:['USA','FRA','USA','SAU','GBR','CAN','KOR','FRA','USA','GBR','USA','CAN','JOR','USA','DEU','USA','USA','GBR','USA','SAU','FRA','USA','FRA','USA','SAU','GBR','USA','FRA','CAN','USA','GBR','USA','SAU','DEU','USA','CAN','FRA','USA','JOR','USA','GBR','CAN','USA','SAU','FRA','USA','GBR','USA','SAU','GBR'][i],
    platform:['PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC'][i],
    sr: 9320 - i*4 - Math.floor(Math.random()*6),
    change: [0,-1,+2,-3,+1,0,+4,-1,+2,-2,0,+1,-3,+2,0,-1,+3,0,-2,+1,+2,0,-1,+3,-2,0,+1,-4,+2,0,-1,+3,0,-2,+4,0,-3,+1,-1,+2,0,-2,+3,-1,0,+2,-4,+1,0,-2][i],
  })),
  // ── Ranks 201-250 ──
  ...Array.from({length:50}, (_,i) => ({
    rank: 201+i, player: ['Meteor','Nova2','Orbit','Pulse2','Quake','Realm','Spark','Titan2','Umbra','Vega',
      'Wisp','Xenon','Yolo','Zodiac','Apex2','Beta2','Crest','Drift','Echo2','Flair',
      'Gust','Halo2','Icon','Jive','Karma2','Lore','Myth','Neon','Opus2','Peak',
      'Quest','Riot','Surge','Torq','Urge','Vast','Wave','Xcel','Yarn','Zest',
      'Aura','Burn','Core','Dash','Evade','Fire2','Grip','Hype','Ideal','Jolt2'][i],
    team:'-', teamSlug:'',
    region:['NA','EU','NA','MENA','NA','EU','NA','MENA','EU','NA','EU','NA','NA','EU','NA','MENA','EU','NA','NA','EU','MENA','NA','EU','NA','MENA','EU','NA','EU','NA','NA','EU','MENA','NA','NA','EU','MENA','NA','EU','NA','NA','MENA','EU','NA','NA','EU','MENA','NA','EU','NA','MENA'][i],
    country:['USA','GBR','CAN','SAU','USA','FRA','USA','SAU','GBR','USA','DEU','USA','CAN','FRA','USA','JOR','GBR','USA','USA','FRA','SAU','USA','GBR','CAN','SAU','FRA','USA','GBR','USA','CAN','DEU','SAU','USA','USA','FRA','JOR','USA','GBR','CAN','USA','SAU','FRA','USA','CAN','GBR','SAU','USA','FRA','USA','SAU'][i],
    platform:['PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC','PS5','PC','PC','PC','PC','PC','PC','PC','PC','PC','PC'][i],
    sr: 9120 - i*3 - Math.floor(Math.random()*6),
    change: [+1,0,-2,+3,0,-1,+2,-3,0,+1,-2,0,+3,-1,0,-4,+2,0,-1,+1,+3,-2,0,+1,-3,+2,0,-1,+4,0,-2,+1,0,-3,+2,-1,0,+3,-2,0,+1,-4,+2,0,-1,+3,-2,+1,0,-1][i],
  })),
];

// ── Top 250 CoD MP Ranked — 19 juin 2026 ─────────────────────
const MP_TOP_250 = [
  // ── CDL pros — dominent le MP ranked ──
  { rank:1,  player:'Simp',       team:'FaZe Vegas',         teamSlug:'faze-vegas',           region:'NA',   country:'USA', platform:'PC',  sr:15252, change:0   },
  { rank:2,  player:'Shotzzy',    team:'OpTic Texas',        teamSlug:'optic-texas',          region:'NA',   country:'USA', platform:'PC',  sr:15084, change:+1  },
  { rank:3,  player:'Cellium',    team:'Riyadh Falcons',     teamSlug:'riyadh-falcons',       region:'NA',   country:'USA', platform:'PC',  sr:14928, change:-1  },
  { rank:4,  player:'Drazah',     team:'FaZe Vegas',         teamSlug:'faze-vegas',           region:'NA',   country:'USA', platform:'PC',  sr:14762, change:+2  },
  { rank:5,  player:'aBeZy',      team:'LA Thieves',         teamSlug:'la-thieves',           region:'NA',   country:'USA', platform:'PC',  sr:14615, change:-1  },
  { rank:6,  player:'Dashy',      team:'OpTic Texas',        teamSlug:'optic-texas',          region:'NA',   country:'USA', platform:'PC',  sr:14450, change:0   },
  { rank:7,  player:'HyDra',      team:'LA Thieves',         teamSlug:'la-thieves',           region:'EU',   country:'FRA', platform:'PC',  sr:14292, change:+3  },
  { rank:8,  player:'CleanX',     team:'Toronto KOI',        teamSlug:'toronto-koi',          region:'EU',   country:'DNK', platform:'PC',  sr:14152, change:-2  },
  { rank:9,  player:'Pred',       team:'Riyadh Falcons',     teamSlug:'riyadh-falcons',       region:'APAC', country:'AUS', platform:'PC',  sr:14004, change:+1  },
  { rank:10, player:'Huke',       team:'OpTic Texas',        teamSlug:'optic-texas',          region:'NA',   country:'USA', platform:'PC',  sr:13840, change:-1  },
  { rank:11, player:'Mercules',   team:'OpTic Texas',        teamSlug:'optic-texas',          region:'NA',   country:'USA', platform:'PC',  sr:13712, change:+2  },
  { rank:12, player:'Ghosty',     team:'Paris GM',           teamSlug:'paris-gentle-mates',   region:'EU',   country:'FRA', platform:'PC',  sr:13581, change:-3  },
  { rank:13, player:'Exnid',      team:'Riyadh Falcons',     teamSlug:'riyadh-falcons',       region:'MENA', country:'SAU', platform:'PC',  sr:13442, change:+4  },
  { rank:14, player:'MettalZ',    team:'Miami Heretics',     teamSlug:'miami-heretics',       region:'EU',   country:'ESP', platform:'PC',  sr:13321, change:0   },
  { rank:15, player:'RenKoR',     team:'Miami Heretics',     teamSlug:'miami-heretics',       region:'EU',   country:'ESP', platform:'PC',  sr:13201, change:+1  },
  { rank:16, player:'SupeR',      team:'Miami Heretics',     teamSlug:'miami-heretics',       region:'EU',   country:'ESP', platform:'PC',  sr:13092, change:-2  },
  { rank:17, player:'Kremp',      team:'G2 Minnesota',       teamSlug:'g2-minnesota',         region:'NA',   country:'USA', platform:'PC',  sr:13014, change:+5  },
  { rank:18, player:'Skyz',       team:'G2 Minnesota',       teamSlug:'g2-minnesota',         region:'EU',   country:'FRA', platform:'PC',  sr:12892, change:-1  },
  { rank:19, player:'Envoy',      team:'G2 Minnesota',       teamSlug:'g2-minnesota',         region:'NA',   country:'USA', platform:'PC',  sr:12784, change:0   },
  { rank:20, player:'Nastie',     team:'G2 Minnesota',       teamSlug:'g2-minnesota',         region:'EU',   country:'GBR', platform:'PC',  sr:12672, change:+2  },
  { rank:21, player:'Abuzah',     team:'FaZe Vegas',         teamSlug:'faze-vegas',           region:'EU',   country:'BEL', platform:'PC',  sr:12562, change:-3  },
  { rank:22, player:'Lurqxx',     team:'Carolina Ravens',    teamSlug:'carolina-royal-ravens', region:'EU',  country:'GBR', platform:'PC',  sr:12452, change:+1  },
  { rank:23, player:'Exceed',     team:'Carolina Ravens',    teamSlug:'carolina-royal-ravens', region:'EU',  country:'GBR', platform:'PC',  sr:12342, change:-1  },
  { rank:24, player:'Spart',      team:'Boston Breach',      teamSlug:'boston-breach',        region:'NA',   country:'USA', platform:'PC',  sr:12234, change:0   },
  { rank:25, player:'Afro',       team:'Boston Breach',      teamSlug:'boston-breach',        region:'EU',   country:'GBR', platform:'PC',  sr:12124, change:+3  },
  { rank:26, player:'TJHaLy',    team:'Boston Breach',      teamSlug:'boston-breach',        region:'NA',   country:'USA', platform:'PC',  sr:12016, change:-2  },
  { rank:27, player:'Purj',       team:'Boston Breach',      teamSlug:'boston-breach',        region:'NA',   country:'USA', platform:'PC',  sr:11908, change:+1  },
  { rank:28, player:'Fire',       team:'Carolina Ravens',    teamSlug:'carolina-royal-ravens', region:'EU',  country:'GBR', platform:'PC',  sr:11802, change:0   },
  { rank:29, player:'Standy',     team:'Carolina Ravens',    teamSlug:'carolina-royal-ravens', region:'NA',  country:'USA', platform:'PC',  sr:11694, change:-4  },
  { rank:30, player:'Insight',    team:'Toronto KOI',        teamSlug:'toronto-koi',          region:'EU',   country:'GBR', platform:'PC',  sr:11588, change:+2  },
  { rank:31, player:'Kips',       team:'Toronto KOI',        teamSlug:'toronto-koi',          region:'NA',   country:'USA', platform:'PC',  sr:11484, change:-1  },
  { rank:32, player:'Abe',        team:'Toronto KOI',        teamSlug:'toronto-koi',          region:'NA',   country:'USA', platform:'PC',  sr:11378, change:+1  },
  { rank:33, player:'ReeaL',      team:'Miami Heretics',     teamSlug:'miami-heretics',       region:'EU',   country:'ESP', platform:'PC',  sr:11274, change:-2  },
  { rank:34, player:'Ghosty',     team:'Paris GM',           teamSlug:'paris-gentle-mates',   region:'EU',   country:'FRA', platform:'PC',  sr:11170, change:+4  },
  { rank:35, player:'Sib',        team:'Paris GM',           teamSlug:'paris-gentle-mates',   region:'EU',   country:'GBR', platform:'PC',  sr:11068, change:-3  },
  { rank:36, player:'Estreal',    team:'Paris GM',           teamSlug:'paris-gentle-mates',   region:'EU',   country:'FRA', platform:'PC',  sr:10966, change:0   },
  { rank:37, player:'JoeDeceives',team:'Paris GM',           teamSlug:'paris-gentle-mates',   region:'EU',   country:'GBR', platform:'PC',  sr:10864, change:+1  },
  { rank:38, player:'Lunarz',     team:'Vancouver Surge',    teamSlug:'vancouver-surge',      region:'NA',   country:'USA', platform:'PC',  sr:10764, change:-2  },
  { rank:39, player:'Nero',       team:'Vancouver Surge',    teamSlug:'vancouver-surge',      region:'NA',   country:'USA', platform:'PC',  sr:10662, change:+2  },
  { rank:40, player:'Mamba',      team:'Vancouver Surge',    teamSlug:'vancouver-surge',      region:'NA',   country:'MEX', platform:'PC',  sr:10562, change:-1  },
  { rank:41, player:'Hide',       team:'Cloud9 NY',          teamSlug:'cloud9-new-york',      region:'NA',   country:'USA', platform:'PC',  sr:10464, change:+3  },
  { rank:42, player:'Encourage',  team:'Cloud9 NY',          teamSlug:'cloud9-new-york',      region:'NA',   country:'USA', platform:'PC',  sr:10366, change:0   },
  { rank:43, player:'Nejra',      team:'Cloud9 NY',          teamSlug:'cloud9-new-york',      region:'EU',   country:'GBR', platform:'PC',  sr:10270, change:-4  },
  { rank:44, player:'Wevy',       team:'Cloud9 NY',          teamSlug:'cloud9-new-york',      region:'NA',   country:'USA', platform:'PC',  sr:10172, change:+1  },
  { rank:45, player:'Scrappy',    team:'LA Thieves',         teamSlug:'la-thieves',           region:'NA',   country:'USA', platform:'PC',  sr:10076, change:-2  },
  { rank:46, player:'Nium',       team:'LA Thieves',         teamSlug:'la-thieves',           region:'EU',   country:'GBR', platform:'PC',  sr:9980,  change:+2  },
  { rank:47, player:'Abuzah',     team:'Vancouver Surge',    teamSlug:'vancouver-surge',      region:'EU',   country:'BEL', platform:'PC',  sr:9886,  change:0   },
  { rank:48, player:'Clayster',   team:'-',                  teamSlug:'',                     region:'NA',   country:'USA', platform:'PC',  sr:9792,  change:+5  },
  { rank:49, player:'Formal',     team:'-',                  teamSlug:'',                     region:'NA',   country:'USA', platform:'PC',  sr:9700,  change:-3  },
  { rank:50, player:'Karma',      team:'-',                  teamSlug:'',                     region:'NA',   country:'USA', platform:'PC',  sr:9608,  change:+1  },
  // ── Ranks 51-250 : streamers, amateurs haut niveau, semi-pros ──
  ...Array.from({length:200}, (_,i) => ({
    rank: 51+i,
    player: ['Jkap','Reptar','Priestahh','Detain','Asim','Zer0','Fero','Cammy','Slasher','Enable',
      'Methodz','Mboze','Sharp','Theory','Rated2','Grizz','Alec','Crimsix2','Kap','Nuck',
      'Slacked2','Gunless','ZooMaa','Parasite','MiRx','Halo','Octane','Owakening','Peirce','Rally',
      'Havok','Denz','Ryze','Scout','Hyped2','Censor','Aqua','Smash','Lamar2','Zack2',
      'ProoF','Zooma2','Havox','Snivy','Crits','Elms','Jurd','Standy2','Ultra2','Tommy2',
      'Lyndon2','Blaze2','Cruz2','Kade','Lyric','Maven','Nexus','Orbit2','Pixel','Quinn',
      'Reign','Solar','Talon','Urban','Valor2','Wyvern','Xross','Yoshi','Zeal','Alpha',
      'Bravo','Cipher','Delta','Echo2','Foxtrot','Gamma','Hotel','India','Juliet','Kilo',
      'Lima','Mike','November','Oscar','Papa','Quebec','Romeo','Sierra','Tango','Uniform',
      'Victor','Whiskey','X-Ray','Yankee','Zulu','Ace2','Blitz','Charge','Doom','Ember',
      'Fang','Gale2','Helix','Impact','Jinx2','Kage','Lance','Mist','Nomad','Oasis',
      'Pyre','Quest2','Rift','Sable','Taunt','Umbra2','Vex','Warp','Xen','Yoke',
      'Zap','Arson','Brick','Clash','Dagger','Echo3','Fist','Grim','Hoist','Ire',
      'Jest','Knell','Lore2','Mend','Null','Opal','Pact','Quell','Rave','Sleet',
      'Tusk','Urge2','Vile','Weld','Xeric','Yore','Zoom','Able','Bard','Cast',
      'Dire','Ebon','Faze2','Gild','Heft','Ikon','Jibe','Keen','Lithe','Meld',
      'Nigh','Ogle','Pave','Quay','Rend','Sift','Tare','Ulna','Veer','Wane',
      'Xyla','Yaw','Zoeic','Agro','Bole','Crew','Dote','Edgy','Fell','Glut',
      'Hewn','Idly','Jape','Kern','Lave','Mere','Nave','Ogre','Pelf','Quip',
      'Roue','Spry','Tole','Uvea','Vend','Weft','Xylo','Yerk','Zoic','Alms'][i] || `Player${51+i}`,
    team:'-', teamSlug:'',
    region:['NA','NA','NA','EU','NA','NA','EU','NA','EU','NA'][i%10],
    country:['USA','USA','USA','GBR','USA','CAN','FRA','USA','GBR','USA'][i%10],
    platform:i%7===0?'PS5':i%11===0?'Xbox':'PC',
    sr: Math.max(9000, 9600 - i*3 - Math.floor(Math.random()*15)),
    change: [-1,0,+1,-2,+2,0,-3,+1,0,-1][i%10],
  })),
];

// ── Seed initial au chargement du module ─────────────────────
seedFromStatic(WZ_TOP_250.map(e => ({ ...e, gamertag: e.player })), 'warzone');
seedFromStatic(MP_TOP_250.map(e => ({ ...e, gamertag: e.player })), 'mp');

// ── Route GET /api/ranked/:mode ───────────────────────────────
router.get('/:mode', async (req, res) => {
  const mode = ['warzone','mp'].includes(req.params.mode) ? req.params.mode : 'warzone';
  const staticEntries = mode === 'mp' ? MP_TOP_250 : WZ_TOP_250;

  const payload = await getTop250(mode, staticEntries);
  res.json(payload);
});

module.exports = router;
